language: node_js
node_js:
  - '8'
  - '10'
  - '11'
cache:
  directories:
    - 'node_modules'
git:
  depth: 5
before_install:
  - npm i -g npm@latest
install:
  - npm ci
  - npm run build
  - npm install -g codecov
script:
  - npm run lint
  - npm test
after_success: npm coverage && codecov
